site_name: freesmartphone.org
site_url: http://www.freesmartphone.org
site_favicon: favicon.ico
repo_url: https://github.com/freesmartphone/freesmartphone.github.io
site_description: Documentation of the freesmartphone.org initiative
site_author: FSO Team
markdown_extensions: [smartypants]
theme: readthedocs

pages:
- [index.md, Home]
- [about.md, About]
- [history.md, History]
- [contribute.md, Contribute]
- [usage-intro.md, Resource Handling]
- [pim-intro.md, PIM Handling]
- [implementations.md, Implementations]
- [specifications.md, Specifications, Introduction]
# <generated docs> I wish we could specify wildcards here...
- [specs/org.freesmartphone.Audio.Manager.md, Specifications, org.freesmartphone.Audio.Manager]
- [specs/org.freesmartphone.Context.Client.md, Specifications, org.freesmartphone.Context.Client]
- [specs/org.freesmartphone.Context.Manager.md, Specifications, org.freesmartphone.Context.Manager]
- [specs/org.freesmartphone.Data.World.md, Specifications, org.freesmartphone.Data.World]
- [specs/org.freesmartphone.Device.AmbientLight.md, Specifications, org.freesmartphone.Device.AmbientLight]
- [specs/org.freesmartphone.Device.Audio.md, Specifications, org.freesmartphone.Device.Audio]
- [specs/org.freesmartphone.Device.Display.md, Specifications, org.freesmartphone.Device.Display]
- [specs/org.freesmartphone.Device.IdleNotifier.md, Specifications, org.freesmartphone.Device.IdleNotifier]
- [specs/org.freesmartphone.Device.Info.md, Specifications, org.freesmartphone.Device.Info]
- [specs/org.freesmartphone.Device.Input.md, Specifications, org.freesmartphone.Device.Input]
- [specs/org.freesmartphone.Device.LED.md, Specifications, org.freesmartphone.Device.LED]
- [specs/org.freesmartphone.Device.Orientation.md, Specifications, org.freesmartphone.Device.Orientation]
- [specs/org.freesmartphone.Device.PowerControl.md, Specifications, org.freesmartphone.Device.PowerControl]
- [specs/org.freesmartphone.Device.PowerSupply.md, Specifications, org.freesmartphone.Device.PowerSupply]
- [specs/org.freesmartphone.Device.Proximity.md, Specifications, org.freesmartphone.Device.Proximity]
- [specs/org.freesmartphone.Device.RealtimeClock.md, Specifications, org.freesmartphone.Device.RealtimeClock]
- [specs/org.freesmartphone.Device.Vibrator.md, Specifications, org.freesmartphone.Device.Vibrator]
- [specs/org.freesmartphone.Error.md, Specifications, org.freesmartphone.Error]
- [specs/org.freesmartphone.Events.md, Specifications, org.freesmartphone.Events]
- [specs/org.freesmartphone.GSM.CB.md, Specifications, org.freesmartphone.GSM.CB]
- [specs/org.freesmartphone.GSM.Call.md, Specifications, org.freesmartphone.GSM.Call]
- [specs/org.freesmartphone.GSM.CallForwarding.md, Specifications, org.freesmartphone.GSM.CallForwarding]
- [specs/org.freesmartphone.GSM.Debug.md, Specifications, org.freesmartphone.GSM.Debug]
- [specs/org.freesmartphone.GSM.Device.md, Specifications, org.freesmartphone.GSM.Device]
- [specs/org.freesmartphone.GSM.Error.md, Specifications, org.freesmartphone.GSM.Error]
- [specs/org.freesmartphone.GSM.HZ.md, Specifications, org.freesmartphone.GSM.HZ]
- [specs/org.freesmartphone.GSM.MUX.md, Specifications, org.freesmartphone.GSM.MUX]
- [specs/org.freesmartphone.GSM.Monitor.md, Specifications, org.freesmartphone.GSM.Monitor]
- [specs/org.freesmartphone.GSM.Network.md, Specifications, org.freesmartphone.GSM.Network]
- [specs/org.freesmartphone.GSM.PDP.md, Specifications, org.freesmartphone.GSM.PDP]
- [specs/org.freesmartphone.GSM.SIM.md, Specifications, org.freesmartphone.GSM.SIM]
- [specs/org.freesmartphone.GSM.SMS.md, Specifications, org.freesmartphone.GSM.SMS]
- [specs/org.freesmartphone.GSM.VoiceMail.md, Specifications, org.freesmartphone.GSM.VoiceMail]
- [specs/org.freesmartphone.Info.md, Specifications, org.freesmartphone.Info]
- [specs/org.freesmartphone.Network.md, Specifications, org.freesmartphone.Network]
- [specs/org.freesmartphone.Notification.md, Specifications, org.freesmartphone.Notification]
- [specs/org.freesmartphone.PIM.Call.md, Specifications, org.freesmartphone.PIM.Call]
- [specs/org.freesmartphone.PIM.CallQuery.md, Specifications, org.freesmartphone.PIM.CallQuery]
- [specs/org.freesmartphone.PIM.Calls.md, Specifications, org.freesmartphone.PIM.Calls]
- [specs/org.freesmartphone.PIM.Contact.md, Specifications, org.freesmartphone.PIM.Contact]
- [specs/org.freesmartphone.PIM.ContactQuery.md, Specifications, org.freesmartphone.PIM.ContactQuery]
- [specs/org.freesmartphone.PIM.Contacts.md, Specifications, org.freesmartphone.PIM.Contacts]
- [specs/org.freesmartphone.PIM.Date.md, Specifications, org.freesmartphone.PIM.Date]
- [specs/org.freesmartphone.PIM.DateQuery.md, Specifications, org.freesmartphone.PIM.DateQuery]
- [specs/org.freesmartphone.PIM.Dates.md, Specifications, org.freesmartphone.PIM.Dates]
- [specs/org.freesmartphone.PIM.Fields.md, Specifications, org.freesmartphone.PIM.Fields]
- [specs/org.freesmartphone.PIM.Message.md, Specifications, org.freesmartphone.PIM.Message]
- [specs/org.freesmartphone.PIM.MessageQuery.md, Specifications, org.freesmartphone.PIM.MessageQuery]
- [specs/org.freesmartphone.PIM.Messages.md, Specifications, org.freesmartphone.PIM.Messages]
- [specs/org.freesmartphone.PIM.Note.md, Specifications, org.freesmartphone.PIM.Note]
- [specs/org.freesmartphone.PIM.NoteQuery.md, Specifications, org.freesmartphone.PIM.NoteQuery]
- [specs/org.freesmartphone.PIM.Notes.md, Specifications, org.freesmartphone.PIM.Notes]
- [specs/org.freesmartphone.PIM.Task.md, Specifications, org.freesmartphone.PIM.Task]
- [specs/org.freesmartphone.PIM.TaskQuery.md, Specifications, org.freesmartphone.PIM.TaskQuery]
- [specs/org.freesmartphone.PIM.Tasks.md, Specifications, org.freesmartphone.PIM.Tasks]
- [specs/org.freesmartphone.PIM.Types.md, Specifications, org.freesmartphone.PIM.Types]
- [specs/org.freesmartphone.Phone.Call.md, Specifications, org.freesmartphone.Phone.Call]
- [specs/org.freesmartphone.Phone.md, Specifications, org.freesmartphone.Phone]
- [specs/org.freesmartphone.Preferences.Service.md, Specifications, org.freesmartphone.Preferences.Service]
- [specs/org.freesmartphone.Preferences.md, Specifications, org.freesmartphone.Preferences]
- [specs/org.freesmartphone.Resource.md, Specifications, org.freesmartphone.Resource]
- [specs/org.freesmartphone.Time.Alarm.md, Specifications, org.freesmartphone.Time.Alarm]
- [specs/org.freesmartphone.Usage.md, Specifications, org.freesmartphone.Usage]
# </generated docs>

