site_name: freesmartphone.org
site_url: http://www.freesmartphone.org
site_favicon: favicon.ico
repo_url: https://github.com/freesmartphone/freesmartphone.github.io
site_description: Documentation of the freesmartphone.org initiative
site_author: FSO Team
markdown_extensions: [smartypants]
theme: readthedocs

pages:
- [index.md, Home]
- [about.md, About]
- [history.md, History]
- [contribute.md, Contribute]
- [usage-intro.md, Resource Handling]
- [pim-intro.md, PIM Handling]
- [specifications.md, Specifications, Introduction]












- [implementations.md, Implementations]
